### ISSUE TITLE
no code for control the laser

### ISSUE THREAD

**Issue by mkeyno** [HakanBastedt/Marlin4Due#1]
hi @HakanBastedt ,
I've check your code again but can't find any code for laser manipulation , also I cant find M05 or M03 code to control laser as like the turnkey code

BR

**Comment by HakanBastedt** [comment]
The laser code is in the **Laser** branch, You should find M3 at line 3132 in Marlin_main.cpp for example. Also check out M649.

**Comment by mkeyno** [comment]
yes , now I found it, thanks, however I was disgusting about standardization the codes with couple of guy[s in this link ](https://groups.google.com/forum/?#!forum/opensource-laser) and I mention all the cnc cutter(laser , plasma,oxyfule,..) developer presume the cutting tool is ideal ready whereas in real machine you should have close loop control on your tools (such as Mach3), tools such as plasma or flame need to pass initiate process and it take time and no body could  grantee this going last. in laser machine ready state check by laser power , I think we should  have function such as setup_killpin() and check after  checkHitEndstops();  function in loop()
I was hopping the marlin developers could gather  in github and create the standard firmware for cutting machines and I hope you could join 
also I might add for safety reason most power tools in cnc machine are active low and I suggest you consider this option

my best regards

**Comment by mkeyno** [comment]
also please check my cnc shield , I would be appreciated to have your comments
https://github.com/mkeyno/Due-Shield-CNC-Laser

**Comment by HakanBastedt** [comment]
Not ideal, but it works. Considering Marlin comes from 3D printing it seems to have the functions needed for X-Y functions like laser. Marlin does lack the concept of "tool" and G2-G3 are in X-Y plane only so it is not ideal for everything. Perhaps it is missing more things as well.

Feedback for readiness can be had with the "M226" command, wait for pin high/low. I have never used plasma so don't know if that is enough.

In this version of Marlin there is Kill pin functionality already, follow the loop() into idle() and manage_activity() and there you find it. HAS_KILL and KILL_PIN need to be defined. On RAMPS-FD it is the E-STOP pin down to the right.

In the TurnkeyTyranny version (and also here) there is the option to select laser firing on high or low. HIGH_TO_FIRE is the define for that.

**Comment by mkeyno** [comment]
thanks @HakanBastedt , have you tried the Repetier Host to control the laser machine?let me share my experience with it,   when I pause or stop(icon) the machine , it continue the perform g-code current line  until get new g-code command ,so due to location  of g-code line, in most  time leaser beam left on , which is so dangerous for high power laser tube , hence I was thinking it must be fast way to shutdown the laser beam in case of unexpected event , we can used the ESP pin to control the board reset pin  , but in most time we need pause action  instead of abort action , 
by the way  , have you check the @MagoKimbra laser codes , it seems he used different way  to fire the laser 
also I really appreciated to if you could look at my cnc due shield ,I've tried just like the GRBL shield break our all  control pin such as abort,resume, pause , peripheral tools ready, ..

**Comment by mkeyno** [comment]
@HakanBastedt  where are you body?

**Comment by HakanBastedt** [comment]
Well I am here, using my laser :) https://www.youtube.com/watch?v=AaAx0MbhCxo

I use repetier host as well and just confirm what you write. One thing is how to get the pause-command to Marlin. Via serial communication is not the right way, A pin can be watched in the same way as the kill pin. Then the next thing is what to do? Shut off laser can be done instantaneously. But pausing in the middle of a movement is a challenge. Ok, stopping can be done, but resuming - I don't know. Between stepper blocks should be easier, but in the middle of a stepper block?

So far I have an E-stop that shuts off the laser in the power supply. When that is done I can stop Marlin in the usual way.

Do you have esp8266 working well for you? I made a quick test and with the lua version I tested it was not able to keep up the speed at even 115200 baud. The idea though is pretty neat, but it must be faster than what I tested.

I looked at MagoKimra's work, an impressive work but the laser functionality seems pretty basic as far as I could see, just a pin switch on, off and pwm. No raster, no synchronization with movements. I am impressed that you find so many different versions of Marlin for Due laser.

Your board is done in Eagle I suppose. Sorry I don't use Eagle.

This version comes along pretty well now. I have gotten some pretty impressive raster speeds
40000 mm/min at 0.2 mm dotsize
35000 mm/min at 0.1 mm dotsize
25000 mm/min at 0.05 mm dotsize

When cutting the speed is not important, some 10 mm/sec or so. Also running high speed with both axles make the whole machine shake around and possibly the laser nozzle to deflect enough to distort the movement.

**Comment by mkeyno** [comment]
hi @HakanBastedt , glad to come back , actually I ran the  debate and talk with many developer while referencing to your code , I suggest them to join the forum for make  firmware for cutting machine , meanwhile I discuss with couple of guys to how  use your code for control the height of laser head or plasma torch during the cutting , 
Right now Manually  Control the laser head height is possible with Marlin function such as [action_laser_focus_custom(),](https://github.com/HakanBastedt/Marlin4Due/blob/Laser/Marlin/ultralcd.cpp#L106-L126)  and I think ,in two ways we can control the  tools heights  during printing our cutting
One with help  of separate modules and one is totally implemented  in firmware
In the first method (hard way) we could use the Arduino module to command the z axis whenever new bias with pre set  g-code height come out, and when adjustment performed active the readiness pin  which is controlled by g-code M266 command before each  cutting   
In the second way we could use the function such as [laser_set_focus(currentZ)](https://github.com/HakanBastedt/Marlin4Due/blob/Laser/Marlin/ultralcd.cpp#L1208) in loop function , in this case we need use I2C to request the height from sensor module    
hope have your idea soon
any way , have you work with chines CNC laser , it's pause key is actually paused any action in any time and you can resume it easily without lost any code , I think  they must monitor pin status such as kill pin or abort pin by interrupt and that interrupt  has prior to stepper timer interrupt. if I correctly recall, in ATMEGA chip which is base of most Arduino board there is nothings such as interrupt priority level as it is in ATXMEGA  series, fortunately we use the ARM core and it is possible to prioritize interrupts 

also Markus send me [code for serial transparent](https://github.com/Links2004/arduinoWebSockets/issues/61),  I put in Arduino and test only his bare code and it is totally work with very good speed , but I haven't test it all features yet in my web host ,but [ Peter](https://github.com/openhardwarecoza/LaserWeb2) & [Luc](https://github.com/luc-github) promises to test the code soon 
thanks again

**Comment by HakanBastedt** [comment]
I followed your track to http://www.aliexpress.com/item/CO2-Laser-Head-Auto-Focus-Focusing-Sensor-for-Automatic-Up-Down-Table-Laser-Engraver-Cutter/32329036592.html?ws_ab_test=searchweb201556_0,searchweb201602_4_10036_10035_10034_507_10020_10001_10002_10017_10010_10005_10011_10006_10003_10021_10004_10022_10009_10008_2030000_10018_10019,searchweb201603_9&btsid=350d69b3-8c0b-4d59-9942-762109cf7163 Looks interesting, what is the technology behind this? Is there a description of it somewhere? I can see myself using that device and making code to have it work. 

In the case of height adjustment _during_ firing, this need to be done with a feedback loop, much in the same way as the temperature for extruders in 3D printers. This of course assume the height sensor is able to deliver proper height values at all times. A PID regulator can then adjust the height of the table on the fly. You have to invent a criteria for when the table is "close enough" to the intended distance to serve as a criteria for when the distance is ready and the laser can start. Compare with the few seconds of waiting when the extruder temperature stabilizes around the setpoint.

I looked in the stepper isr code what should be needed to pause instantly at any movement. I assume it can be done but there is timer calculation code which is beyond me. Also there is a practical side to it, at least when engraving at high speed. Just stopping the stepping abruptly will 100% certainty result in the motors loosing steps, and then the position is lost anyway. For a slower cutting movement I can see the point. If you have code to contribute that would be awesome, I myself don't have the motivation and skills to do it. What I can easily do is to attach an interrupt to a pin - no problems whatsoever on Due - to shut down the laser intensity. Then secondly what does such an action mean in terms of handling the stream of g-code from serial os SD? Flushing everything? Or what? 

I looked at Markus code, but realize for me to test this I need to practically be spoon-fed.

**Comment by mkeyno** [comment]
hi @HakanBastedt , please look at [this google group](https://groups.google.com/forum/#!topic/opensource-laser/3QfXocAsFNM/discussion) , couple of guys discuss about auto focus 
I think this module use 300kHz ultrasonic for precise measurement but I'm not sure and might be 
Hal sensor ,   
for the height control approach I suggest, let's open the new issue and  summarize all possible way to  control cutting tools in Marlin Due then we call the enthusiast developer  to join this topic 
do you agree upon?
one of these cool guy is @ambrop72 with aprinter firmware which is base on Due and  successfully implemented the laser feature in his code , I hope he could help us to find best option for auto focus laser machine

**Comment by HakanBastedt** [comment]
From what I have found out it may be a mechanical switch. Check this photo, it acts like an end-stop switch http://kfdown.a.aliimg.com/kf/HTB1q6HMMXXXXXXpXpXXq6xXFXXXa.jpg
It will work for setting static focus but not dynamic focus/height setting.

**Comment by mkeyno** [comment]
it is only the controller and not related to laser THC , please check this reference 

[LFS-DM-T43 Live Focus System (Digital) Operation Manual](http://en.rd-acs.com/Private/Files/c8fef1393caf3b73.pdf)

**Comment by HakanBastedt** [comment]
But that is something completely different. A whole system with capacitive sensor and amplifier and control system.
The picture in my post was how the seller said the aliexpress sensor should be connected to a controller. There is a plus and a minus cable and then the third cable that goes where an end-stop switch normally sits. If it isn't a mechanical switch, it seems to act like one.

**Comment by mkeyno** [comment]
maybe it is PNP 2 wire proximity sensor with pre set height before printing , [some guys told me they use such vendor ](http://www.aotoro.com/english/Product/Proximity-Switch-2.html) , please check the sensors
